/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AptitudeRouteImport } from './routes/aptitude'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HrTrainingRouteImport } from './routes/hr-training'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResumeAnalyzerRouteImport } from './routes/resume-analyzer'
import { Route as TechnicalTrainingRouteImport } from './routes/technical-training'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AptitudeRoute = AptitudeRouteImport.update({
  id: '/aptitude',
  path: '/aptitude',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HrTrainingRoute = HrTrainingRouteImport.update({
  id: '/hr-training',
  path: '/hr-training',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeAnalyzerRoute = ResumeAnalyzerRouteImport.update({
  id: '/resume-analyzer',
  path: '/resume-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalTrainingRoute = TechnicalTrainingRouteImport.update({
  id: '/technical-training',
  path: '/technical-training',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aptitude': typeof AptitudeRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hr-training': typeof HrTrainingRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/technical-training': typeof TechnicalTrainingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aptitude': typeof AptitudeRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hr-training': typeof HrTrainingRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/technical-training': typeof TechnicalTrainingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aptitude': typeof AptitudeRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hr-training': typeof HrTrainingRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/technical-training': typeof TechnicalTrainingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aptitude'
    | '/dashboard'
    | '/forgot-password'
    | '/hr-training'
    | '/login'
    | '/register'
    | '/resume-analyzer'
    | '/technical-training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aptitude'
    | '/dashboard'
    | '/forgot-password'
    | '/hr-training'
    | '/login'
    | '/register'
    | '/resume-analyzer'
    | '/technical-training'
  id:
    | '__root__'
    | '/'
    | '/aptitude'
    | '/dashboard'
    | '/forgot-password'
    | '/hr-training'
    | '/login'
    | '/register'
    | '/resume-analyzer'
    | '/technical-training'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AptitudeRoute: typeof AptitudeRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HrTrainingRoute: typeof HrTrainingRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResumeAnalyzerRoute: typeof ResumeAnalyzerRoute
  TechnicalTrainingRoute: typeof TechnicalTrainingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aptitude': {
      id: '/aptitude'
      path: '/aptitude'
      fullPath: '/aptitude'
      preLoaderRoute: typeof AptitudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-training': {
      id: '/hr-training'
      path: '/hr-training'
      fullPath: '/hr-training'
      preLoaderRoute: typeof HrTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-analyzer': {
      id: '/resume-analyzer'
      path: '/resume-analyzer'
      fullPath: '/resume-analyzer'
      preLoaderRoute: typeof ResumeAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-training': {
      id: '/technical-training'
      path: '/technical-training'
      fullPath: '/technical-training'
      preLoaderRoute: typeof TechnicalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AptitudeRoute: AptitudeRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HrTrainingRoute: HrTrainingRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResumeAnalyzerRoute: ResumeAnalyzerRoute,
  TechnicalTrainingRoute: TechnicalTrainingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
